###########################################################
# Makefile for CS530 Assignment #3
# Destyni Ta
# 820552974
############################################################
#File: Makefile

exp: exp.c
        gcc exp.c exp


exp.o: exp.c exp.h
        gcc -c exp.c


clean: 
        rm *.o exp
############################################################
